### PR TITLE
use time seed

### PR DESCRIPTION
**Pull request by WIZARD-CXY**
use time seed for generating random number

### CODE REVIEW

**Comment by WIZARD-CXY** [comment]
Good to go!

**Comment by ggaaooppeenngg** [comment]
One of changes are merged into l3 branch, [commit e7928b](https://github.com/gophergala/learn-Go-the-hard-way/commit/e7928bbb871d606409512d354895ae46f1ae4aad). Can you rebase your branch into l3 branch to resolve conflicts?

**Comment by WIZARD-CXY** [comment]
OK

**Comment by WIZARD-CXY** [comment]
I think you should merge l3 or cherrypick to master, right?

**Comment by ggaaooppeenngg** [comment]
Historically, I pushed commits on the master, and made tags as well. I think it is not coder-friendly, just leaving a tag on a independent branch is more reasonable.

**Pull request closed without merging**
